// <auto-generated />
using System;
using CarWash.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarWash.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarWashDbContext))]
    [Migration("20260531135426_Rf010CancelamentoAgendamento")]
    partial class Rf010CancelamentoAgendamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarWash.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelado_em");

                    b.Property<Guid?>("CanceladoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelado_por");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<int>("DuracaoTotalMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duracao_total_min");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fim");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamptz")
                        .HasColumnName("inicio");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_id");

                    b.Property<string>("StatusRaw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("agendado")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_total");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.Property<int>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_agendamentos");

                    b.HasIndex("CriadoPor")
                        .HasDatabaseName("ix_agendamentos_criado_por");

                    b.HasIndex("ResponsavelId")
                        .HasDatabaseName("ix_agendamentos_responsavel_id");

                    b.HasIndex("StatusRaw")
                        .HasDatabaseName("idx_ag_status");

                    b.HasIndex("ClienteId", "Inicio")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_ag_cliente");

                    b.HasIndex("FilialId", "Inicio")
                        .HasDatabaseName("idx_ag_filial_inicio");

                    b.HasIndex("VeiculoId", "Inicio")
                        .HasDatabaseName("idx_ag_veiculo");

                    b.ToTable("agendamentos", "public", t =>
                        {
                            t.HasCheckConstraint("ck_ag_duracao_total", "duracao_total_min >= 0");

                            t.HasCheckConstraint("ck_ag_inicio_menor_fim", "inicio < fim");

                            t.HasCheckConstraint("ck_ag_status", "status IN ('agendado','em_andamento','cancelado','finalizado')");

                            t.HasCheckConstraint("ck_ag_valor_total", "valor_total >= 0");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.AgendamentoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<string>("EventoRaw")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("evento");

                    b.Property<DateTime>("OcorridoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("ocorrido_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_agendamento_historico");

                    b.HasIndex("EventoRaw")
                        .HasDatabaseName("idx_hist_evento");

                    b.HasIndex("OcorridoEm")
                        .HasDatabaseName("idx_hist_ocorrido_em");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_agendamento_historico_usuario_id");

                    b.HasIndex("AgendamentoId", "OcorridoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_hist_agendamento");

                    b.ToTable("agendamento_historico", "public", t =>
                        {
                            t.HasCheckConstraint("ck_hist_evento", "evento IN ('CRIADO','EDITADO','CANCELADO','FINALIZADO')");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.AgendamentoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DuracaoAplicada")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_aplicada");

                    b.Property<decimal>("PrecoAplicado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_aplicado");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.HasKey("Id")
                        .HasName("pk_agendamento_itens");

                    b.HasIndex("AgendamentoId")
                        .HasDatabaseName("idx_item_agendamento");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("idx_item_servico");

                    b.HasIndex("AgendamentoId", "ServicoId")
                        .IsUnique()
                        .HasDatabaseName("uk_item_agendamento_servico");

                    b.ToTable("agendamento_itens", "public", t =>
                        {
                            t.HasCheckConstraint("ck_item_duracao", "duracao_aplicada > 0");

                            t.HasCheckConstraint("ck_item_preco", "preco_aplicado >= 0");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entidade");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("evento");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_audit_correlation");

                    b.HasIndex("CriadoEm")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_criado_em");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_audit_logs_usuario_id");

                    b.HasIndex("Entidade", "EntidadeId")
                        .HasDatabaseName("idx_audit_entidade");

                    b.HasIndex("Evento", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_evento");

                    b.ToTable("audit_logs", "public");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("AtualizadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por_usuario_id");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("celular");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("EnderecoBairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_bairro");

                    b.Property<string>("EnderecoCep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("endereco_cep");

                    b.Property<string>("EnderecoCidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_cidade");

                    b.Property<string>("EnderecoComplemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_complemento");

                    b.Property<string>("EnderecoLogradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("endereco_logradouro");

                    b.Property<string>("EnderecoNumero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("EnderecoUf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("endereco_uf")
                        .IsFixedLength();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uk_clientes_cnpj")
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("uk_clientes_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_clientes_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_clientes_nome");

                    b.ToTable("clientes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_clientes_cpf_ou_cnpj", "cpf IS NOT NULL OR cnpj IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ambiente");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("FilialId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<bool>("Habilitada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("habilitada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("ValorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valor_json");

                    b.HasKey("Id")
                        .HasName("pk_feature_flags");

                    b.HasIndex("AtualizadoPor")
                        .HasDatabaseName("ix_feature_flags_atualizado_por");

                    b.HasIndex("FilialId")
                        .HasDatabaseName("ix_feature_flags_filial_id");

                    b.ToTable("feature_flags", "public");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Filiado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_filiados");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_filiados_cliente_id");

                    b.HasIndex("Cpf")
                        .HasDatabaseName("idx_filiados_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("ClienteId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("uk_filiados_cliente_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.ToTable("filiados", "public", t =>
                        {
                            t.HasCheckConstraint("ck_filiados_cpf_ou_rg", "cpf IS NOT NULL OR rg IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Filial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CelulasAtivas")
                        .HasColumnType("integer")
                        .HasColumnName("celulas_ativas");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_filiais");

                    b.HasIndex("Ativa")
                        .HasDatabaseName("idx_filiais_ativa")
                        .HasFilter("ativa = true");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("uk_filiais_nome");

                    b.ToTable("filiais", "public", t =>
                        {
                            t.HasCheckConstraint("ck_filiais_celulas_faixa", "celulas_ativas BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.IdempotenciaRequisicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("escopo");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<Guid?>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<string>("RespostaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resposta_json");

                    b.Property<int>("StatusHttp")
                        .HasColumnType("integer")
                        .HasColumnName("status_http");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotencia_requisicoes");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("ix_idempotencia_expira_em");

                    b.HasIndex("IdempotencyKey", "Escopo")
                        .IsUnique()
                        .HasDatabaseName("uq_idempotencia_key_escopo");

                    b.ToTable("idempotencia_requisicoes", "public");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("destino");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendente")
                        .HasColumnName("status");

                    b.Property<int>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UltimaTentativa")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ultima_tentativa");

                    b.HasKey("Id")
                        .HasName("pk_notificacoes");

                    b.HasIndex("Status", "CriadoEm")
                        .HasDatabaseName("idx_notif_status");

                    b.HasIndex("AgendamentoId", "Tipo", "Canal", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_notif_dedupe");

                    b.ToTable("notificacoes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_notif_canal", "canal IN ('email','whatsapp','sms')");

                            t.HasCheckConstraint("ck_notif_tentativas", "tentativas >= 0");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.OutboxEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agregado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("agregado");

                    b.Property<Guid>("AgregadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agregado_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DisponivelEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("disponivel_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("evento");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processado_em");

                    b.Property<string>("StatusRaw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pendente")
                        .HasColumnName("status");

                    b.Property<int>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas");

                    b.HasKey("Id")
                        .HasName("pk_outbox_eventos");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_outbox_idempotency");

                    b.HasIndex("StatusRaw", "DisponivelEm")
                        .HasDatabaseName("idx_outbox_status_disponivel")
                        .HasFilter("status IN ('pendente','falha')");

                    b.ToTable("outbox_eventos", "public", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_status", "status IN ('pendente','processando','processado','falha')");

                            t.HasCheckConstraint("ck_outbox_tentativas", "tentativas >= 0");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DuracaoMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_min");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id")
                        .HasName("pk_servicos");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("idx_servicos_ativo")
                        .HasFilter("ativo = true");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("uk_servicos_nome");

                    b.ToTable("servicos", "public", t =>
                        {
                            t.HasCheckConstraint("ck_servicos_duracao_max", "duracao_min <= 1440");

                            t.HasCheckConstraint("ck_servicos_duracao_positiva", "duracao_min > 0");

                            t.HasCheckConstraint("ck_servicos_preco", "preco > 0");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_until");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamptz")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailValor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("PerfilRaw")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<int>("TentativasInvalidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_invalidas");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("idx_usuarios_ativo")
                        .HasFilter("ativo = false");

                    b.HasIndex("EmailValor")
                        .IsUnique()
                        .HasDatabaseName("uk_usuarios_email");

                    b.ToTable("usuarios", "public", t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_perfil", "perfil IN ('ADMIN','FUNCIONARIO')");

                            t.HasCheckConstraint("ck_usuarios_tentativas_invalidas", "tentativas_invalidas >= 0");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.UsuarioPreferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TemaRaw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("claro")
                        .HasColumnName("tema");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_preferencias");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("uk_pref_usuario_id");

                    b.ToTable("usuario_preferencias", "public", t =>
                        {
                            t.HasCheckConstraint("ck_pref_tema", "tema IN ('claro','escuro')");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.UsuarioSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expira_em");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origem");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revogado_em");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_sessoes");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("idx_sessoes_expira_em");

                    b.HasIndex("RevogadoEm")
                        .HasDatabaseName("idx_sessoes_revogado_em")
                        .HasFilter("revogado_em IS NOT NULL");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_sessoes_usuario_id");

                    b.ToTable("usuario_sessoes", "public");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("fabricante");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_veiculos_cliente_id");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("uk_veiculos_placa");

                    b.ToTable("veiculos", "public", t =>
                        {
                            t.HasCheckConstraint("ck_veiculos_ano", "ano IS NULL OR (ano BETWEEN 1900 AND 2100)");

                            t.HasCheckConstraint("ck_veiculos_placa_formato", "placa ~ '^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$'");
                        });
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ag_cliente");

                    b.HasOne("CarWash.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ag_criado_por");

                    b.HasOne("CarWash.Domain.Entities.Filial", null)
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ag_filial");

                    b.HasOne("CarWash.Domain.Entities.Filiado", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ag_responsavel");

                    b.HasOne("CarWash.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ag_veiculo");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.AgendamentoHistorico", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Agendamento", null)
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hist_agendamento");

                    b.HasOne("CarWash.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hist_usuario");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.AgendamentoItem", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Agendamento", null)
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_agendamento");

                    b.HasOne("CarWash.Domain.Entities.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_servico");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_usuario");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.FeatureFlag", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flag_atualizado_por");

                    b.HasOne("CarWash.Domain.Entities.Filial", null)
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_flag_filial");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Filiado", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_filiados_cliente");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Agendamento", null)
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notif_agendamento");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.UsuarioPreferencia", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("CarWash.Domain.Entities.UsuarioPreferencia", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pref_usuario");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.UsuarioSessao", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_usuario");
                });

            modelBuilder.Entity("CarWash.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("CarWash.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
